# Nginx: servidor web leve e rápido
# "alpine" é uma versão ultra-leve do Linux (~5MB)
FROM nginx:alpine

# Copiamos nosso HTML para dentro do servidor Nginx
COPY . /usr/share/nginx/html/

# Porta padrão do Nginx
EXPOSE 80ng generate service services/api