# Nginx: servidor web leve e rápido
# "alpine" é uma versão ultra-leve do Linux (~5MB)
FROM nginx:alpine

# Copiamos nosso HTML para dentro do servidor Nginx
COPY index.html /usr/share/nginx/html/index.html

# Porta padrão do Nginx
EXPOSE 80